server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched

  rabbitmq:
    host: localhost
    port: 5672
    username: ft
    password: 123456
    connection-timeout: 5s
